"""
core/boilerplate_generator.py

Generates a production-ready project zip from a session's architecture data.
Returns a BytesIO zip containing: package.json, src/index.js, docker-compose.yml,
.env.example, README.md, and a basic Dockerfile.
"""
import io
import json
import zipfile


def _detect_stack(arch: dict) -> dict:
    frontend = (arch.get("frontend") or "").lower()
    backend = (arch.get("backend") or "").lower()
    database = (arch.get("database") or "").lower()
    hosting = (arch.get("hosting") or "").lower()

    return {
        "use_react": "react" in frontend or "next" in frontend,
        "use_vue": "vue" in frontend,
        "use_express": "express" in backend or "node" in backend,
        "use_fastapi": "fastapi" in backend or "python" in backend or "django" in backend,
        "use_postgres": "postgres" in database or "pg" in database,
        "use_mongo": "mongo" in database,
        "use_mysql": "mysql" in database or "maria" in database,
        "use_redis": "redis" in database,
        "use_docker": "aws" in hosting or "fly" in hosting or "gcp" in hosting or "docker" in hosting,
    }


def _package_json(arch: dict, project_name: str, stack: dict) -> str:
    deps = {"dotenv": "^16.0.0"}
    dev_deps = {}

    if stack["use_express"]:
        deps.update({"express": "^4.18.0", "cors": "^2.8.5", "helmet": "^7.0.0", "morgan": "^1.10.0"})
        dev_deps.update({"nodemon": "^3.0.0"})

    if stack["use_postgres"]:
        deps["pg"] = "^8.11.0"
        deps["pg-pool"] = "^3.6.0"
    if stack["use_mongo"]:
        deps["mongoose"] = "^8.0.0"
    if stack["use_mysql"]:
        deps["mysql2"] = "^3.6.0"
    if stack["use_redis"]:
        deps["redis"] = "^4.6.0"

    apis = arch.get("apis") or []
    api_str = " ".join(apis).lower() if isinstance(apis, list) else str(apis).lower()
    if "stripe" in api_str:
        deps["stripe"] = "^14.0.0"
    if "aws" in api_str:
        deps["@aws-sdk/client-s3"] = "^3.0.0"
    if "sendgrid" in api_str or "resend" in api_str:
        deps["resend"] = "^3.0.0"

    pkg = {
        "name": project_name.lower().replace(" ", "-"),
        "version": "0.1.0",
        "description": f"Auto-generated by DevKit.AI — {arch.get('backend', 'Node.js')} backend",
        "main": "src/index.js",
        "scripts": {
            "start": "node src/index.js",
            "dev": "nodemon src/index.js" if stack["use_express"] else "node src/index.js",
            "lint": "eslint ."
        },
        "dependencies": deps,
        "devDependencies": dev_deps,
        "engines": {"node": ">=18.0.0"}
    }
    return json.dumps(pkg, indent=2)


def _server_js(arch: dict, stack: dict) -> str:
    db = arch.get("database", "")
    port = "process.env.PORT || 3000"

    db_section = ""
    if stack["use_postgres"]:
        db_section = """
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
"""
    elif stack["use_mongo"]:
        db_section = """
const mongoose = require('mongoose');
mongoose.connect(process.env.MONGO_URI).then(() => console.log('MongoDB connected'));
"""
    elif stack["use_mysql"]:
        db_section = """
const mysql = require('mysql2/promise');
const pool = mysql.createPool(process.env.DATABASE_URL);
"""

    return f"""'use strict';
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
{db_section}
const app = express();

// ─── Middleware ────────────────────────────────────────────────
app.use(helmet({ crossOriginEmbedderPolicy: false, contentSecurityPolicy: false }));
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({{ extended: true }}));

// ─── Health Check ──────────────────────────────────────────────
app.get('/healthz', (req, res) => {{
  res.json({{ status: 'ok', service: '{arch.get("backend", "API")}', timestamp: new Date() }});
}});

// ─── API Routes ───────────────────────────────────────────────
// TODO: Import and mount your route modules here
// const userRoutes = require('./routes/users');
// app.use('/api/users', userRoutes);

// ─── 404 Handler ──────────────────────────────────────────────
app.use('*', (req, res) => {{
  res.status(404).json({{ error: 'Route not found' }});
}});

// ─── Error Handler ─────────────────────────────────────────────
app.use((err, req, res, next) => {{
  console.error(err.stack);
  res.status(500).json({{ error: 'Internal server error' }});
}});

// ─── Start Server ──────────────────────────────────────────────
const PORT = {port};
app.listen(PORT, '0.0.0.0', () => {{
  console.log(`🚀 Server running on http://localhost:${{PORT}}`);
  console.log(`📦 Stack: {arch.get("backend", "Node.js")} + {db}`);
}});
"""


def _docker_compose(arch: dict, project_name: str, stack: dict) -> str:
    name = project_name.lower().replace(" ", "_")
    services = f"""version: '3.9'

name: {name}

services:
  app:
    build: .
    ports:
      - "${{PORT:-3000}}:3000"
    environment:
      - NODE_ENV=development
    env_file: .env
    depends_on:"""

    db_service = ""
    if stack["use_postgres"]:
        services += "\n      - postgres"
        db_service = """
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-devkit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devkitpass}
      POSTGRES_DB: ${POSTGRES_DB:-devkit_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:"""
    elif stack["use_mongo"]:
        services += "\n      - mongo"
        db_service = """
  mongo:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-devkit}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-devkitpass}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:"""
    elif stack["use_mysql"]:
        services += "\n      - mysql"
        db_service = """
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-devkit_db}
      MYSQL_USER: ${MYSQL_USER:-devkit}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-devkitpass}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:"""
    else:
        services = services.rstrip("depends_on:")

    if stack["use_redis"]:
        services += "\n      - redis"
        db_service += """

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-devkitredis}"""

    return services + "\n" + db_service + "\n"


def _env_example(arch: dict, stack: dict) -> str:
    lines = [
        "# ─── App ──────────────────────────────────────────",
        "NODE_ENV=development",
        "PORT=3000",
        "API_SECRET=change_me_in_production",
        "",
        "# ─── Database ─────────────────────────────────────",
    ]
    if stack["use_postgres"]:
        lines += [
            "POSTGRES_USER=devkit",
            "POSTGRES_PASSWORD=devkitpass",
            "POSTGRES_DB=devkit_db",
            "DATABASE_URL=postgresql://devkit:devkitpass@localhost:5432/devkit_db",
        ]
    elif stack["use_mongo"]:
        lines += [
            "MONGO_USER=devkit",
            "MONGO_PASSWORD=devkitpass",
            "MONGO_URI=mongodb://devkit:devkitpass@localhost:27017/devkit_db",
        ]
    elif stack["use_mysql"]:
        lines += [
            "MYSQL_USER=devkit",
            "MYSQL_PASSWORD=devkitpass",
            "MYSQL_DATABASE=devkit_db",
            "DATABASE_URL=mysql://devkit:devkitpass@localhost:3306/devkit_db",
        ]
    if stack["use_redis"]:
        lines += ["REDIS_PASSWORD=devkitredis", "REDIS_URL=redis://:devkitredis@localhost:6379"]

    apis = arch.get("apis") or []
    api_str = " ".join(apis).lower() if isinstance(apis, list) else str(apis).lower()
    lines += ["", "# ─── External APIs ────────────────────────────────"]
    if "stripe" in api_str:
        lines += ["STRIPE_SECRET_KEY=sk_test_...", "STRIPE_WEBHOOK_SECRET=whsec_..."]
    if "aws" in api_str:
        lines += ["AWS_ACCESS_KEY_ID=...", "AWS_SECRET_ACCESS_KEY=...", "AWS_REGION=us-east-1", "AWS_S3_BUCKET=..."]
    if "sendgrid" in api_str:
        lines += ["SENDGRID_API_KEY=SG...."]
    if "resend" in api_str:
        lines += ["RESEND_API_KEY=re_..."]
    lines += ["", "# ─── Auth ─────────────────────────────────────────"]
    lines += ["JWT_SECRET=change_this_to_a_long_random_string", "JWT_EXPIRES_IN=7d"]

    return "\n".join(lines) + "\n"


def _dockerfile(stack: dict) -> str:
    return """FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package*.json ./
RUN npm ci --omit=dev

FROM base AS runner
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 3000
CMD ["node", "src/index.js"]
"""


def _readme(arch: dict, project_name: str, instruction_md: str) -> str:
    apis = arch.get("apis") or []
    api_str = ", ".join(apis) if isinstance(apis, list) else str(apis)
    return f"""# {project_name}

> Auto-generated by **DevKit.AI** — production-ready boilerplate

## Stack

| Layer | Technology |
|---|---|
| Frontend | {arch.get("frontend", "—")} |
| Backend | {arch.get("backend", "—")} |
| Database | {arch.get("database", "—")} |
| Hosting | {arch.get("hosting", "—")} |
| APIs | {api_str or "—"} |

## Quick Start

```bash
# 1. Install dependencies
npm install

# 2. Configure environment
cp .env.example .env
# Edit .env with your values

# 3. Start with Docker Compose (recommended)
docker compose up -d

# 4. Start the dev server
npm run dev
```

## Available Scripts

| Command | Description |
|---|---|
| `npm run dev` | Start dev server with hot reload |
| `npm start` | Start production server |

---

{instruction_md}
"""


def generate_boilerplate_zip(session: dict) -> io.BytesIO:
    """
    Generate a zip file from a session's final_outputs.architecture.
    Returns a BytesIO buffer ready to stream.
    """
    outputs = session.get("final_outputs") or {}
    arch = outputs.get("architecture") or {}
    instruction_md = outputs.get("instruction_md") or "# AI-Generated Instructions\n\nSee README for setup."
    project_name = session.get("project_name") or "devkit-project"
    stack = _detect_stack(arch)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("package.json", _package_json(arch, project_name, stack))
        zf.writestr("src/index.js", _server_js(arch, stack))
        zf.writestr("src/routes/.gitkeep", "")
        zf.writestr("src/middleware/.gitkeep", "")
        zf.writestr("src/models/.gitkeep", "")
        zf.writestr("docker-compose.yml", _docker_compose(arch, project_name, stack))
        zf.writestr(".env.example", _env_example(arch, stack))
        zf.writestr("Dockerfile", _dockerfile(stack))
        zf.writestr("README.md", _readme(arch, project_name, instruction_md))
        zf.writestr(".gitignore", "node_modules/\n.env\ndist/\n*.log\n.DS_Store\n")
        zf.writestr(
            "src/healthz.js",
            "module.exports = (req, res) => res.json({ status: 'ok', uptime: process.uptime() });\n"
        )

    buf.seek(0)
    return buf
